1 gnd uris
dini-ag-kim/hs-oer-lom-profil pull request #10
Opened 2020-02-11 11:52 UTC by mic-men

Hinweis zur Personenidentifikation über GND-ID eingefügt.
@acka47 kannst Du bitte den Link in der Liste (B.2) noch ergänzen? Ich wusste nicht, was da richtig ist.

2020-02-12 14:52 UTC, acka47 requested changes
Siehe meine Änderungsvorschläge. Ich kann die Änderungen auch gerne direkt comitten, wenn du einverstanden bist @mic-men .

2020-02-12 14:52 UTC, acka47 commented on draft/index.html
> -Anzumerken ist die Möglichkeit, die [[?ORCID]] der Person als Tag `URL` mit anzugeben,
Ich würde es wie folgt formulieren:

> Anzumerken ist die Möglichkeit, die [[?ORCID]] oder die [[?GND]] -ID der Person
als Tag `URL` mit anzugeben, die genutzt werden SOLL, wenn die Information zur Verfügung steht.
Der entsprechende Identifier MUSS bei Angabe als HTTP-URI angegeben werden, z.B. 
`https://orcid.org/0000-0001-9083-7442` oder `https://d-nb.info/gnd/14326723X`.

2020-02-12 14:52 UTC, acka47 commented on draft/index.html
>  Für Organisationen gilt ein ähnlicher Vorschlag, hier SOLL als `URL` der Eintrag
Das würde ioch wie folgt formulieren (sinnvollerweise sollten wir hier auch GND erlauben):

> Für Organisationen gilt ein ähnlicher Vorschlag, hier SOLL als `URL` der URI des
entsprechenden [[?Wikidata]]-Items genannt werden oder die [[?GND]]-URI,
also z. B. für die Universität Tübingen `http://www.wikidata.org/entity/Q153978` 
oder `https://d-nb.info/gnd/36187-2`.

2020-02-12 15:00 UTC, acka47 commented
Ich habe jetzt mal meine Vorschläge gepusht (2976eb62a2a823ea01748b9641d78d0b40f3a6d9), können wir ja gerne noch weiter anpassen.

2020-02-13 08:22 UTC, mic-men commented
Ich bin mit allen Änderungen so einverstanden.

2020-02-14 10:16 UTC, acka47 commented
Wie am Telefon mit @mic-men besprochen, schließe ich diesen PR und merge stattdessen #12, der nur die GND-Änderungne enthält.

2020-02-14 10:16 UTC, closed without merging