3 learningresourcetype
dini-ag-kim/hs-oer-lom-profil pull request #9
Opened 2020-02-11 11:12 UTC by mic-men

Ich habe die Learning Resource Types entsprechend der SKOS Repräsentation angepasst.
@sebastian-meyer , ich habe mich bemüht, mich an die ReSpec-Vorgaben zu halten, dabei musste <id> in die mehrfach vorkommenden Elemente verschoben werden, bitte nochmal kontrollieren.
Außerdem fiel mir auf, dass <source> sowohl den Partner <value> als auch <id> / <entry> haben kann. Nur noch für 1 (LOMv.1.0) der bei <source> angeg. Werte ist der Partner <value>. Ich wusste aber nicht, wie das regelkonform umzusetzen ist, momentan ist es aber nicht ideal. Kannst Du das mit Deiner Erfahrung noch anpassen?

Zusätzlich noch kleinere Änderungen, die hier mit drin sind (ich bemühe mich zukünftig um noch mehr Trennung):
- in der Klassifikation die <source> geändert von 'Hochschulfaecher' in die W3ID-URL
- Auflistung der lt. LOM möglichen anderen Werte für <role> entfernt
- Verweis jetzt auf LOM 1.2.4 statt 1.2.1, im Verzeichnis dabei Link auf die allg. Seite gesetzt, da es kein passenden speziellen Link gibt, bitte nochmal überprüfen u. ggflls. verbessern.

2020-02-12 14:19 UTC, acka47 requested changes
Einige Dinge sollten noch angepasst werden, siehe Kommentare.

2020-02-12 14:19 UTC, acka47 commented on draft/index.html
> +        Link zur Repräsentation dar.
Ich finde insbesondere den letzten Satz unklar. Worauf bezieht sich da "Repräsentation"? M.E. kann der Satz einfach weggelassen werden. Formulierungsvorschlag:

```suggestion
        Für die möglichen Werte wurde mit „Hochschulcampus Ressourcentypen“ 
        ein kontrolliertes Vokabular in Anlehnung an LOM spezifiziert ([[!SKOS-LRT]]), 
        in dem jeder mögliche Wert durch einen URI identifiziert ist.
```

2020-02-12 14:19 UTC, acka47 commented on draft/index.html
> +Taxonomie mittels einer ID, die den Anspruch auf dauerhafte Gültigkeit erhebt.
```suggestion
Das Element enthält einen URI, mittels dessen die konkrete Kategorie eindeutig identifiziert wird, 
der das Objekt im Rahmen der verwendeten Taxonomie zugeordnet wird.
```

2020-02-12 14:19 UTC, acka47 commented on draft/index.html
> +eingerichtete Service für permanente Identifier im WWW genutzt. Damit bekommt jeder
Ich glaube, den Satz kann man hier und unten weglassen. Das ist ein Implementierungsdetail, das an dieser Stelle nicht erläutert werden muss.

2020-02-12 14:19 UTC, acka47 commented on draft/index.html
> +eingerichtete Service für permanente Identifier im WWW genutzt. Damit bekommt jedes
s.o.

2020-02-12 14:19 UTC, acka47 commented on draft/index.html
> +Die ID-Nr. besteht dabei aus einem Kleinbuchstaben und einer oder mehreren Ziffern.
Das kann m.E. auch raus.

2020-02-13 08:51 UTC, mic-men commented
Bin auch hier mit allem einverstanden. Habe nicht herausgefunden, wie ich das übernehmen kann, können wir vielleicht zusammen machen.

2020-02-20 16:44 UTC, sebastian-meyer commented
> @sebastian-meyer , ich habe mich bemüht, mich an die ReSpec-Vorgaben zu halten, dabei musste 'id' in die mehrfach vorkommenden Elemente verschoben werden, bitte nochmal kontrollieren.
> Außerdem fiel mir auf, dass 'source' sowohl den Partner 'value' als auch 'id' / 'entry' haben kann. Nur noch für 1 (LOMv.1.0) der bei 'source' angeg. Werte ist der Partner 'value'. Ich wusste aber nicht, wie das regelkonform umzusetzen ist, momentan ist es aber nicht ideal. Kannst Du das mit Deiner Erfahrung noch anpassen?

Es gibt keinen mir bekannten Weg, in ReSpec zwei gleichlautende Elemente mit unterschiedlichen Definitionen zu versehen. Es darf in einem ReSpec-Dokument also nur eine Definition für `source` geben. Du müsstest also innerhalb dieser Definition beide Fälle beschreiben.

2020-02-21 10:20 UTC, merged